# please make sure everything is string

# project basis
project_name: "jiahe_thermal_debug"
project_path: "/media/jonasjiang/p4510/Jiahe_Thermal_IMU_Debug/thermal_data_10_16"
run_to_bags: ""

# ros topics
system_id: ""
thermal_topic: "/thermal/image"

# pointcloud task properties
max_points: "50000000"
print_timestamp: "both"
invert_thermal: "false"

# tasks to run
# csv_task: "true"
# pointcloud_task: "true"
# mocap_task: "true"
# rgb_task: "true"
thermal_task: "true"
# csv_old_task: "true"
# odom_task: "true"

