# please make sure everything is string

# project basis
project_name: "2022-08-08_Mil19"
project_path: "/Users/jonasjiang/Workspace/AirLab/dataset/2022-08-19_mil19"
run_to_bags: ""

# ros topics
system_id: "cmu_rc3"
odom_topic: "/cmu_rc3/aft_mapped_to_init_imu"
stats_topic: "/cmu_rc3/super_odometry_stats"
pointcloud_topic: "/cmu_rc3/velodyne_cloud_registered_imu"
mocap_topic: "/mocap_data"
rgb_topic: "/cmu_rc3/camera_1/image_raw"
thermal_topic: "/thermal/image"

# pointcloud task properties
max_points: "50000000"

# tasks to run
# csv_task: "true"
# pointcloud_task: "true"
mocap_task: "true"
# rgb_task: "true"
# thermal_task: "true"
# odom_task: "true"
