# please make sure everything is string

# project basis
project_name: "2022-08-18_multi_floor"
project_path: "/media/jonasjiang/p4510/2022-08-18_spot_multi_floor"
run_to_bags: "bags"

# ros topics
system_id: "cmu_sp1"
odom_topic: "/cmu_sp1/aft_mapped_to_init_imu"
stats_topic: "/cmu_sp1/super_odometry_stats"
pointcloud_topic: "/cmu_sp1/velodyne_cloud_registered_imu"

# pointcloud task properties
max_points: "50000000"

# tasks to run
csv_task: "true"
# pointcloud_task: "true"
# mocap_task: "true"
# rgb_task: "true"
# thermal_task: "true"
