# please make sure everything is string

# project basis
project_name: "subt_groundtruth"
project_path: "/media/jonasjiang/p4510/subt_localization"
run_to_bags: ""


# ros topics
system_id: ""
odom_topic: "/aft_mapped_to_init_imu"

# pointcloud task properties
max_points: "50000000"

# tasks to run
# csv_task: "true"
# pointcloud_task: "true"
# mocap_task: "true"
# rgb_task: "true"
# thermal_task: "true"
groundtruth_task: "true"